### ISSUE TITLE
Provide option to '--trace' and show output

### ISSUE THREAD

**Issue by bpow** [pegjs/website#19]
Consider this a wishlist feature request to provide an option in the web interface to produce a parser with '--trace' enabled and to show the resulting trace output for debugging purposes.

**Comment by dmajda** [comment]
Yes, this would be useful once 0.9.0 is released. (The PEG.js website always uses the latest officially released PEG.js version and 0.8.0 didn’t have tracing support.)

An easy way to implement this would be to add a checkbox labeled e.g. “Enable tracing” below the “Use results cache” one. Then, add a “Trace” link to the status bar with parse result which would open the captured trace in a popup.

I won’t work on this myself but if anyone is interested, I’ll accept a PR after the 0.9.0 release.

**Comment by dmajda** [comment]
I reconsidered. I decided to keep the online editor simple and not turn it into a full-fledged grammar development IDE. If you want to debug things using tracing, you need to do it outside the editor.
