### ISSUE TITLE
Remember user code in the online editor

### ISSUE THREAD

**Issue by joews** [pegjs/website#20]
It would be neat if the online editor persisted the latest user input across visits, like the [babel.js REPL](https://babeljs.io/repl/) - sometimes I want to go back to the idea code I was working on earlier, and at the moment I need to save the code somewhere locally or start from scratch.

It should be pretty trivial with `localStorage`. I'll happily submit a PR if you think it's a good idea.

**Comment by dmajda** [comment]
I agree this is a good idea, a PR is welcome.
